baseURL = 'https://shared-consulting.netlify.app/'
languageCode = 'en-us'
title = 'Shared Consulting'
theme = 'nord-hugo-book'

[params]
  BookTheme = 'light'
  BookSearch = true
  BookRepo = 'https://github.com/monsieurDuke/shared-consulting' 
  BookDateFormat = '02-02-2002'
  favicon = '/favicon.png'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'nord'
    tabWidth = 4